import ts from 'typescript';
import { describe, expect, it } from 'vitest';
import { emitterManifestFixture, emitterProductionFixture } from './test-fixtures';
import { emitProductionModule } from './production-emitter';

const golden = `// AUTO-GENERATED by loa compose. Do not hand-edit.
// Re-run \`loa compose fixture\` to regenerate.

import type { AssetManifest, Production } from '@/lib/lattice';

export const PROD: Production = {
  characters: [
    {
      description: "Fixture narrator",
      id: "narrator",
      name: "Narrator",
      voice_profile: {
        service: "kokoro",
        voice_id: "af_bella",
      },
    },
  ],
  default_aspect: "16:9",
  funding: {
    donation_links: {},
    donations_received_usd: 0,
    ledger: [],
    planned_improvements: [],
    production_cost_usd: 0,
  },
  id: "fixture",
  provenance: {
    authors: ["Fixture"],
    created_at: "1970-01-01T00:00:00.000Z",
    license: "CC-BY-4.0",
  },
  scenes: [
    {
      id: "intro",
      shots: [
        {
          cues: [
            {
              at: 0.25,
              element_id: "title",
              kind: "visibility",
              visible: true,
            },
          ],
          duration: 1.5,
          elements: [
            {
              id: "title",
              initial_layout: {
                opacity: 1,
                position: [0.5, 0.5, 0],
              },
              kind: "text-overlay",
              text: "Hello \\"Compose\\"",
            },
          ],
          id: "open",
        },
      ],
      title: "Intro",
    },
  ],
  summary: "A deterministic fixture production.",
  tags: ["test"],
  tier: "v0.1",
  title: "Fixture",
  transitions: [],
};

export const MANIFEST: AssetManifest = {
  ledger: [],
  production_id: "fixture",
  slots: {
    "intro.open.vo0": {
      description: "Narration for intro/open.",
      id: "intro.open.vo0",
      kind: "audio-vo",
      takes: [],
    },
  },
};
`;

describe('emitProductionModule', () => {
  it('matches the checked-in golden string', () => {
    const generated = emitProductionModule({
      slug: 'fixture',
      production: emitterProductionFixture(),
      manifest: emitterManifestFixture(),
    });

    expect(generated).toBe(golden);
  });

  it('emits byte-identical output for repeated calls', () => {
    const production = emitterProductionFixture();
    const manifest = emitterManifestFixture();
    const left = emitProductionModule({ slug: 'fixture', production, manifest });
    const right = emitProductionModule({ slug: 'fixture', production, manifest });

    expect(right).toBe(left);
  });

  it('emits syntactically valid TypeScript', () => {
    const source = emitProductionModule({
      slug: 'fixture',
      production: emitterProductionFixture(),
      manifest: emitterManifestFixture(),
    });
    const output = ts.transpileModule(source, {
      compilerOptions: {
        module: ts.ModuleKind.ESNext,
        target: ts.ScriptTarget.ES2022,
      },
      reportDiagnostics: true,
    });
    const diagnostics = output.diagnostics === undefined ? [] : output.diagnostics;

    expect(diagnostics).toEqual([]);
  });
});
