import type { AssetManifest, Production } from '@/lib/lattice';

export interface EmitProductionModuleArgs {
  slug: string;
  production: Production;
  manifest: AssetManifest;
}

export function emitProductionModule(args: EmitProductionModuleArgs): string {
  const header = `// AUTO-GENERATED by loa compose. Do not hand-edit.
// Re-run \`loa compose ${args.slug}\` to regenerate.

import type { AssetManifest, Production } from '@/lib/lattice';

`;
  const prodLiteral = stringifyForTs(args.production);
  const manifestLiteral = stringifyForTs(args.manifest);
  return (
    `${header}` +
    `export const PROD: Production = ${prodLiteral};\n\n` +
    `export const MANIFEST: AssetManifest = ${manifestLiteral};\n`
  );
}

export function stringifyForTs(value: unknown): string {
  return printValue(value, 0);
}

function printValue(value: unknown, depth: number): string {
  if (value === undefined) return 'undefined';
  if (value === null) return 'null';
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number') return printNumber(value);
  if (typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) return printArray(value, depth);
  if (isPlainObject(value)) return printObject(value, depth);
  throw new Error(`cannot emit TypeScript literal for ${typeof value}`);
}

function printNumber(value: number): string {
  if (!Number.isFinite(value)) {
    throw new Error('cannot emit non-finite number in TypeScript literal');
  }
  return String(value);
}

function printArray(value: unknown[], depth: number): string {
  // Arrays preserve composer-runner order; object keys are the byte-stability boundary.
  if (value.length === 0) return '[]';
  if (isShortArray(value)) {
    return `[${value.map((item) => printValue(item, depth)).join(', ')}]`;
  }
  const nextDepth = depth + 1;
  const itemIndent = indent(nextDepth);
  const closeIndent = indent(depth);
  const items = value.map((item) => `${itemIndent}${printValue(item, nextDepth)}`);
  return `[\n${items.join(',\n')},\n${closeIndent}]`;
}

function isShortArray(value: unknown[]): boolean {
  if (value.length > 4) return false;
  for (const item of value) {
    if (item === null) continue;
    const kind = typeof item;
    if (kind === 'string' || kind === 'number' || kind === 'boolean') continue;
    return false;
  }
  return true;
}

function printObject(value: { [key: string]: unknown }, depth: number): string {
  const entries = Object.entries(value)
    .filter((entry) => entry[1] !== undefined)
    .sort(([left], [right]) => left.localeCompare(right));
  if (entries.length === 0) return '{}';

  const nextDepth = depth + 1;
  const propertyIndent = indent(nextDepth);
  const closeIndent = indent(depth);
  const properties = entries.map(([key, entryValue]) =>
    `${propertyIndent}${propertyName(key)}: ${printValue(entryValue, nextDepth)}`,
  );
  return `{\n${properties.join(',\n')},\n${closeIndent}}`;
}

function isPlainObject(value: unknown): value is { [key: string]: unknown } {
  if (value === null) return false;
  if (typeof value !== 'object') return false;
  if (Array.isArray(value)) return false;
  return true;
}

function propertyName(key: string): string {
  if (identifierPattern.test(key) && !reservedWords.has(key)) return key;
  return JSON.stringify(key);
}

function indent(depth: number): string {
  return '  '.repeat(depth);
}

const identifierPattern = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const reservedWords = new Set([
  'abstract',
  'any',
  'as',
  'asserts',
  'async',
  'await',
  'boolean',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'constructor',
  'continue',
  'debugger',
  'declare',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'from',
  'function',
  'get',
  'if',
  'implements',
  'import',
  'in',
  'infer',
  'instanceof',
  'interface',
  'is',
  'keyof',
  'let',
  'module',
  'namespace',
  'never',
  'new',
  'null',
  'number',
  'object',
  'of',
  'package',
  'private',
  'protected',
  'public',
  'readonly',
  'require',
  'return',
  'set',
  'static',
  'string',
  'super',
  'switch',
  'symbol',
  'this',
  'throw',
  'true',
  'try',
  'type',
  'typeof',
  'undefined',
  'unique',
  'unknown',
  'var',
  'void',
  'while',
  'with',
  'yield',
]);
