// AUTO-GENERATED by loa compose. Do not hand-edit.
// Re-run `loa compose world-graph-models` to regenerate.

import type { AssetManifest, Production } from '@/lib/lattice';

export const PROD: Production = {
  characters: [
    {
      description: "Default lesson voice. Conversational, curious, technically rigorous.",
      id: "narrator",
      name: "Narrator",
      voice_profile: {
        service: "kokoro",
        voice_id: "af_bella",
      },
    },
  ],
  default_aspect: "16:9",
  funding: {
    donation_links: {},
    donations_received_usd: 0,
    ledger: [],
    planned_improvements: [],
    production_cost_usd: 0,
  },
  id: "world-graph-models",
  provenance: {
    authors: ["Library of Alexandria Composer"],
    created_at: "1970-01-01T00:00:00.000Z",
    license: "CC-BY-4.0",
  },
  rabbit_holes: [],
  scenes: [
    {
      background: {
        kind: "gradient",
        stops: [
          {
            color: "#0f172a",
            offset: 0,
          },
          {
            color: "#2563eb",
            offset: 1,
          },
        ],
      },
      eyebrow: "Opening Question",
      id: "scene-model-before-policy",
      shots: [
        {
          cues: [
            {
              at: 0,
              element_id: "narrator-opener.eyebrow",
              kind: "transform",
              layout: {
                opacity: 1,
              },
              transition: {
                duration_ms: 200,
                ease: "easeOut",
              },
            },
            {
              at: 0.15,
              element_id: "narrator-opener.title",
              kind: "transform",
              layout: {
                opacity: 1,
                position: [0.5, 0.5, 0],
              },
              transition: {
                duration_ms: 400,
                ease: "easeOut",
              },
            },
          ],
          duration: 7,
          elements: [
            {
              id: "narrator-opener.eyebrow",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.38, 0],
                z_order: 20,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#9ad1ff",
                font: "sans",
                size: "sm",
                weight: 700,
              },
              text: "Opening Question",
            },
            {
              id: "narrator-opener.title",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.53, 0],
                z_order: 21,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#ffffff",
                font: "display",
                size: "4xl",
                weight: 800,
              },
              text: "Model Before Policy",
            },
          ],
          id: "shot-1-1",
          vo: {
            audio: {
              slot_id: "audio-pending-b9880e9b08f54375",
            },
            cast_id: "narrator",
            line: {
              text: "A reinforcement learning agent normally pays for knowledge with real trials, one action and one consequence at a time.",
            },
          },
        },
        {
          dialogue: [
            {
              audio: {
                slot_id: "audio-pending-a81ca8e619ba66e8",
              },
              cast_id: "narrator",
              id: "line-shot-1-2-2",
              line: {
                text: "The agent can ask the model for imagined transitions before it commits to another action in the environment.",
              },
            },
          ],
          duration: 12,
          elements: [],
          id: "shot-1-2",
          vo: {
            audio: {
              slot_id: "audio-pending-39d5f0693bab3457",
            },
            cast_id: "narrator",
            line: {
              text: "A learned world model changes that bargain by turning past experience into a simulator of what might happen next.",
            },
          },
        },
        {
          dialogue: [
            {
              audio: {
                slot_id: "audio-pending-daf01f6c4d2192ce",
              },
              cast_id: "narrator",
              id: "line-shot-1-3-2",
              line: {
                text: "The opening question is not whether the model is perfect, but whether it is good enough to make real trials count for more.",
              },
            },
          ],
          duration: 13,
          elements: [],
          id: "shot-1-3",
          vo: {
            audio: {
              slot_id: "audio-pending-4f037fc5db31a287",
            },
            cast_id: "narrator",
            line: {
              text: "Sample efficiency improves when useful policy updates come from both real interaction and predicted experience.",
            },
          },
        },
      ],
      summary: "Opener for Model Before Policy",
      title: "Model Before Policy",
    },
    {
      background: {
        kind: "gradient",
        stops: [
          {
            color: "#111827",
            offset: 0,
          },
          {
            color: "#0891b2",
            offset: 1,
          },
        ],
      },
      eyebrow: "Latent Imagination",
      id: "scene-dream-space",
      shots: [
        {
          cues: [
            {
              at: 0,
              element_id: "narrator-opener.eyebrow",
              kind: "transform",
              layout: {
                opacity: 1,
              },
              transition: {
                duration_ms: 200,
                ease: "easeOut",
              },
            },
            {
              at: 0.15,
              element_id: "narrator-opener.title",
              kind: "transform",
              layout: {
                opacity: 1,
                position: [0.5, 0.5, 0],
              },
              transition: {
                duration_ms: 400,
                ease: "easeOut",
              },
            },
          ],
          duration: 5,
          elements: [
            {
              id: "narrator-opener.eyebrow",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.38, 0],
                z_order: 20,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#9ad1ff",
                font: "sans",
                size: "sm",
                weight: 700,
              },
              text: "Latent Imagination",
            },
            {
              id: "narrator-opener.title",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.53, 0],
                z_order: 21,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#ffffff",
                font: "display",
                size: "4xl",
                weight: 800,
              },
              text: "Dream Space",
            },
          ],
          id: "shot-2-1",
          vo: {
            audio: {
              slot_id: "audio-pending-ac090a786eb2c74d",
            },
            cast_id: "narrator",
            line: {
              text: "A latent world model does not need to store every pixel as the agent sees it.",
            },
          },
        },
        {
          dialogue: [
            {
              audio: {
                slot_id: "audio-pending-3f056baf1756b3df",
              },
              cast_id: "narrator",
              id: "line-shot-2-2-2",
              line: {
                text: "Inside that compressed space, rollout steps are cheaper than replaying the full world in detail.",
              },
            },
          ],
          duration: 11,
          elements: [],
          id: "shot-2-2",
          vo: {
            audio: {
              slot_id: "audio-pending-de8b6f0a6c5a5ee6",
            },
            cast_id: "narrator",
            line: {
              text: "It learns a compact state that keeps the information needed to predict rewards, observations, and consequences of actions.",
            },
          },
        },
        {
          duration: 7,
          elements: [],
          id: "shot-2-3",
          vo: {
            audio: {
              slot_id: "audio-pending-e8754f50ce774194",
            },
            cast_id: "narrator",
            line: {
              text: "A policy can train inside those predicted futures and test many action sequences before touching the real environment again.",
            },
          },
        },
        {
          duration: 5,
          elements: [],
          id: "shot-2-4",
          vo: {
            audio: {
              slot_id: "audio-pending-34422d701b866cd0",
            },
            cast_id: "narrator",
            line: {
              text: "Latent imagination is useful because it makes planning and policy learning fast enough to repeat.",
            },
          },
        },
      ],
      summary: "Opener for Dream Space",
      title: "Dream Space",
    },
    {
      background: {
        kind: "gradient",
        stops: [
          {
            color: "#18181b",
            offset: 0,
          },
          {
            color: "#dc2626",
            offset: 1,
          },
        ],
      },
      eyebrow: "Failure Mode",
      id: "scene-error-horizon",
      shots: [
        {
          cues: [
            {
              at: 0,
              element_id: "narrator-opener.eyebrow",
              kind: "transform",
              layout: {
                opacity: 1,
              },
              transition: {
                duration_ms: 200,
                ease: "easeOut",
              },
            },
            {
              at: 0.15,
              element_id: "narrator-opener.title",
              kind: "transform",
              layout: {
                opacity: 1,
                position: [0.5, 0.5, 0],
              },
              transition: {
                duration_ms: 400,
                ease: "easeOut",
              },
            },
          ],
          duration: 4,
          elements: [
            {
              id: "narrator-opener.eyebrow",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.38, 0],
                z_order: 20,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#9ad1ff",
                font: "sans",
                size: "sm",
                weight: 700,
              },
              text: "Failure Mode",
            },
            {
              id: "narrator-opener.title",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.53, 0],
                z_order: 21,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#ffffff",
                font: "display",
                size: "4xl",
                weight: 800,
              },
              text: "Error Horizon",
            },
          ],
          id: "shot-3-1",
          vo: {
            audio: {
              slot_id: "audio-pending-8a7e1525f87236ec",
            },
            cast_id: "narrator",
            line: {
              text: "The same imagination that saves samples also creates a new failure mode.",
            },
          },
        },
        {
          dialogue: [
            {
              audio: {
                slot_id: "audio-pending-b48739eead614cf7",
              },
              cast_id: "narrator",
              id: "line-shot-3-2-2",
              line: {
                text: "When the model feeds its own prediction into the next prediction, that small miss can become the starting point for a larger miss.",
              },
            },
          ],
          duration: 14,
          elements: [],
          id: "shot-3-2",
          vo: {
            audio: {
              slot_id: "audio-pending-234b1b4219a0d0f0",
            },
            cast_id: "narrator",
            line: {
              text: "A one-step prediction can look accurate while still carrying a small error in position, reward, or hidden state.",
            },
          },
        },
        {
          duration: 5,
          elements: [],
          id: "shot-3-3",
          vo: {
            audio: {
              slot_id: "audio-pending-945a45d42f124856",
            },
            cast_id: "narrator",
            line: {
              text: "Long imagined rollouts therefore have an error horizon where useful forecasts fade into model fantasy.",
            },
          },
        },
        {
          duration: 6,
          elements: [],
          id: "shot-3-4",
          vo: {
            audio: {
              slot_id: "audio-pending-fd2eb5862ba7790e",
            },
            cast_id: "narrator",
            line: {
              text: "Good model-based control must balance the value of looking ahead against the risk of trusting predictions too far.",
            },
          },
        },
      ],
      summary: "Opener for Error Horizon",
      title: "Error Horizon",
    },
    {
      background: {
        kind: "gradient",
        stops: [
          {
            color: "#0c0a09",
            offset: 0,
          },
          {
            color: "#059669",
            offset: 1,
          },
        ],
      },
      eyebrow: "Object Worlds",
      id: "scene-combinatorial-wall",
      shots: [
        {
          cues: [
            {
              at: 0,
              element_id: "narrator-opener.eyebrow",
              kind: "transform",
              layout: {
                opacity: 1,
              },
              transition: {
                duration_ms: 200,
                ease: "easeOut",
              },
            },
            {
              at: 0.15,
              element_id: "narrator-opener.title",
              kind: "transform",
              layout: {
                opacity: 1,
                position: [0.5, 0.5, 0],
              },
              transition: {
                duration_ms: 400,
                ease: "easeOut",
              },
            },
          ],
          duration: 7,
          elements: [
            {
              id: "narrator-opener.eyebrow",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.38, 0],
                z_order: 20,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#9ad1ff",
                font: "sans",
                size: "sm",
                weight: 700,
              },
              text: "Object Worlds",
            },
            {
              id: "narrator-opener.title",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.53, 0],
                z_order: 21,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#ffffff",
                font: "display",
                size: "4xl",
                weight: 800,
              },
              text: "The Combinatorial Wall",
            },
          ],
          id: "shot-4-1",
          vo: {
            audio: {
              slot_id: "audio-pending-aee1c79da73eb49b",
            },
            cast_id: "narrator",
            line: {
              text: "A single-vector latent state can summarize a scene, but it does not naturally say which part belongs to which object.",
            },
          },
        },
        {
          dialogue: [
            {
              audio: {
                slot_id: "audio-pending-b290d66327718ef9",
              },
              cast_id: "narrator",
              id: "line-shot-4-2-2",
              line: {
                text: "An object-centric representation breaks the scene into reusable entities with their own attributes.",
              },
            },
          ],
          duration: 11,
          elements: [],
          id: "shot-4-2",
          vo: {
            audio: {
              slot_id: "audio-pending-8f56dcd274cad430",
            },
            cast_id: "narrator",
            line: {
              text: "As the number of objects grows, the possible arrangements and interactions grow much faster than the training set.",
            },
          },
        },
        {
          duration: 6,
          elements: [],
          id: "shot-4-3",
          vo: {
            audio: {
              slot_id: "audio-pending-8ba2cecf87512e78",
            },
            cast_id: "narrator",
            line: {
              text: "The model can then ask how these entities relate instead of relearning every whole-scene configuration from scratch.",
            },
          },
        },
        {
          duration: 5,
          elements: [],
          id: "shot-4-4",
          vo: {
            audio: {
              slot_id: "audio-pending-2b568ae74c33ebaf",
            },
            cast_id: "narrator",
            line: {
              text: "This is the combinatorial wall that pushes world models toward objects and relations.",
            },
          },
        },
      ],
      summary: "Opener for The Combinatorial Wall",
      title: "The Combinatorial Wall",
    },
    {
      background: {
        kind: "gradient",
        stops: [
          {
            color: "#111827",
            offset: 0,
          },
          {
            color: "#7c3aed",
            offset: 1,
          },
        ],
      },
      eyebrow: "Graph Assumption",
      id: "scene-relational-bias",
      shots: [
        {
          cues: [
            {
              at: 0,
              element_id: "narrator-opener.eyebrow",
              kind: "transform",
              layout: {
                opacity: 1,
              },
              transition: {
                duration_ms: 200,
                ease: "easeOut",
              },
            },
            {
              at: 0.15,
              element_id: "narrator-opener.title",
              kind: "transform",
              layout: {
                opacity: 1,
                position: [0.5, 0.5, 0],
              },
              transition: {
                duration_ms: 400,
                ease: "easeOut",
              },
            },
          ],
          duration: 6,
          elements: [
            {
              id: "narrator-opener.eyebrow",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.38, 0],
                z_order: 20,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#9ad1ff",
                font: "sans",
                size: "sm",
                weight: 700,
              },
              text: "Graph Assumption",
            },
            {
              id: "narrator-opener.title",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.53, 0],
                z_order: 21,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#ffffff",
                font: "display",
                size: "4xl",
                weight: 800,
              },
              text: "Relational Bias",
            },
          ],
          id: "shot-5-1",
          vo: {
            audio: {
              slot_id: "audio-pending-1fcfa4ce83be9fd9",
            },
            cast_id: "narrator",
            line: {
              text: "A graph builds an assumption into the model: entities are nodes, and possible influences are edges.",
            },
          },
        },
        {
          dialogue: [
            {
              audio: {
                slot_id: "audio-pending-f174f2ecc4d9cd87",
              },
              cast_id: "narrator",
              id: "line-shot-5-2-2",
              line: {
                text: "That relational inductive bias helps the model reuse a learned interaction when the objects are rearranged or the count changes.",
              },
            },
          ],
          duration: 13,
          elements: [],
          id: "shot-5-2",
          vo: {
            audio: {
              slot_id: "audio-pending-9a89ba2c429c44db",
            },
            cast_id: "narrator",
            line: {
              text: "The same update rule can be shared across many pairs of objects instead of being tied to one fixed scene layout.",
            },
          },
        },
        {
          dialogue: [
            {
              audio: {
                slot_id: "audio-pending-ac1c6acc2e3b2775",
              },
              cast_id: "narrator",
              id: "line-shot-5-3-2",
              line: {
                text: "The price is that the model must choose which entities and edges deserve attention.",
              },
            },
          ],
          duration: 10,
          elements: [],
          id: "shot-5-3",
          vo: {
            audio: {
              slot_id: "audio-pending-35f100d4f1512217",
            },
            cast_id: "narrator",
            line: {
              text: "Generalization comes from treating relations as repeatable structure, not as accidental details of one observation.",
            },
          },
        },
      ],
      summary: "Opener for Relational Bias",
      title: "Relational Bias",
    },
    {
      background: {
        kind: "gradient",
        stops: [
          {
            color: "#020617",
            offset: 0,
          },
          {
            color: "#14b8a6",
            offset: 1,
          },
        ],
      },
      eyebrow: "Learned Dynamics",
      id: "scene-message-passing-physics",
      shots: [
        {
          cues: [
            {
              at: 0,
              element_id: "narrator-opener.eyebrow",
              kind: "transform",
              layout: {
                opacity: 1,
              },
              transition: {
                duration_ms: 200,
                ease: "easeOut",
              },
            },
            {
              at: 0.15,
              element_id: "narrator-opener.title",
              kind: "transform",
              layout: {
                opacity: 1,
                position: [0.5, 0.5, 0],
              },
              transition: {
                duration_ms: 400,
                ease: "easeOut",
              },
            },
          ],
          duration: 7,
          elements: [
            {
              id: "narrator-opener.eyebrow",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.38, 0],
                z_order: 20,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#9ad1ff",
                font: "sans",
                size: "sm",
                weight: 700,
              },
              text: "Learned Dynamics",
            },
            {
              id: "narrator-opener.title",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.53, 0],
                z_order: 21,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#ffffff",
                font: "display",
                size: "4xl",
                weight: 800,
              },
              text: "Messages As Physics",
            },
          ],
          id: "shot-6-1",
          vo: {
            audio: {
              slot_id: "audio-pending-893fafccd1167f10",
            },
            cast_id: "narrator",
            line: {
              text: "In a graph dynamics model, prediction begins with object states and an action that may affect one object or the whole scene.",
            },
          },
        },
        {
          dialogue: [
            {
              audio: {
                slot_id: "audio-pending-d64319b617f9ede3",
              },
              cast_id: "narrator",
              id: "line-shot-6-2-2",
              line: {
                text: "A receiving node aggregates those messages with its own state and the action context.",
              },
            },
          ],
          duration: 10,
          elements: [],
          id: "shot-6-2",
          vo: {
            audio: {
              slot_id: "audio-pending-fb76c8d8fa66e005",
            },
            cast_id: "narrator",
            line: {
              text: "Each node sends messages along its edges that describe how it may influence its neighbors.",
            },
          },
        },
        {
          duration: 4,
          elements: [],
          id: "shot-6-3",
          vo: {
            audio: {
              slot_id: "audio-pending-9298caa4b524616e",
            },
            cast_id: "narrator",
            line: {
              text: "The shared dynamics rule updates every object into a predicted next state.",
            },
          },
        },
        {
          duration: 6,
          elements: [],
          id: "shot-6-4",
          vo: {
            audio: {
              slot_id: "audio-pending-817c59e419365f29",
            },
            cast_id: "narrator",
            line: {
              text: "Message passing acts like learned local physics because future motion emerges from repeated object-to-object influence.",
            },
          },
        },
      ],
      summary: "Opener for Messages As Physics",
      title: "Messages As Physics",
    },
    {
      background: {
        kind: "gradient",
        stops: [
          {
            color: "#1f2937",
            offset: 0,
          },
          {
            color: "#f59e0b",
            offset: 1,
          },
        ],
      },
      eyebrow: "Equivariance",
      id: "scene-order-does-not-matter",
      shots: [
        {
          cues: [
            {
              at: 0,
              element_id: "narrator-opener.eyebrow",
              kind: "transform",
              layout: {
                opacity: 1,
              },
              transition: {
                duration_ms: 200,
                ease: "easeOut",
              },
            },
            {
              at: 0.15,
              element_id: "narrator-opener.title",
              kind: "transform",
              layout: {
                opacity: 1,
                position: [0.5, 0.5, 0],
              },
              transition: {
                duration_ms: 400,
                ease: "easeOut",
              },
            },
          ],
          dialogue: [
            {
              audio: {
                slot_id: "audio-pending-3b5d89feda8f41a6",
              },
              cast_id: "narrator",
              id: "line-shot-7-1-2",
              line: {
                text: "If two identical descriptions are listed in a different order, the world has not physically changed.",
              },
            },
          ],
          duration: 10,
          elements: [
            {
              id: "narrator-opener.eyebrow",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.38, 0],
                z_order: 20,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#9ad1ff",
                font: "sans",
                size: "sm",
                weight: 700,
              },
              text: "Equivariance",
            },
            {
              id: "narrator-opener.title",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.53, 0],
                z_order: 21,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#ffffff",
                font: "display",
                size: "4xl",
                weight: 800,
              },
              text: "Order Does Not Matter",
            },
          ],
          id: "shot-7-1",
          vo: {
            audio: {
              slot_id: "audio-pending-028aff37b8904164",
            },
            cast_id: "narrator",
            line: {
              text: "Object slots and graph nodes often arrive in an arbitrary order.",
            },
          },
        },
        {
          dialogue: [
            {
              audio: {
                slot_id: "audio-pending-1b28307ebed8d60f",
              },
              cast_id: "narrator",
              id: "line-shot-7-2-2",
              line: {
                text: "It should not predict a different collision merely because object three was renamed object one.",
              },
            },
          ],
          duration: 11,
          elements: [],
          id: "shot-7-2",
          vo: {
            audio: {
              slot_id: "audio-pending-3339b73b08d12087",
            },
            cast_id: "narrator",
            line: {
              text: "A permutation-equivariant graph model respects that fact by moving predictions with the reordered labels.",
            },
          },
        },
        {
          duration: 3,
          elements: [],
          id: "shot-7-3",
          vo: {
            audio: {
              slot_id: "audio-pending-b6b08b2e87f04a9e",
            },
            cast_id: "narrator",
            line: {
              text: "Order does not matter, but consistent correspondence does.",
            },
          },
        },
      ],
      summary: "Opener for Order Does Not Matter",
      title: "Order Does Not Matter",
    },
    {
      background: {
        kind: "gradient",
        stops: [
          {
            color: "#0f172a",
            offset: 0,
          },
          {
            color: "#16a34a",
            offset: 1,
          },
        ],
      },
      eyebrow: "Structure From Perception",
      id: "scene-learning-the-slots",
      shots: [
        {
          cues: [
            {
              at: 0,
              element_id: "narrator-opener.eyebrow",
              kind: "transform",
              layout: {
                opacity: 1,
              },
              transition: {
                duration_ms: 200,
                ease: "easeOut",
              },
            },
            {
              at: 0.15,
              element_id: "narrator-opener.title",
              kind: "transform",
              layout: {
                opacity: 1,
                position: [0.5, 0.5, 0],
              },
              transition: {
                duration_ms: 400,
                ease: "easeOut",
              },
            },
          ],
          duration: 5,
          elements: [
            {
              id: "narrator-opener.eyebrow",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.38, 0],
                z_order: 20,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#9ad1ff",
                font: "sans",
                size: "sm",
                weight: 700,
              },
              text: "Structure From Perception",
            },
            {
              id: "narrator-opener.title",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.53, 0],
                z_order: 21,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#ffffff",
                font: "display",
                size: "4xl",
                weight: 800,
              },
              text: "Learning The Slots",
            },
          ],
          id: "shot-8-1",
          vo: {
            audio: {
              slot_id: "audio-pending-9e981a90f496937d",
            },
            cast_id: "narrator",
            line: {
              text: "An object-centric world model first has to find the objects before it can reason over them.",
            },
          },
        },
        {
          dialogue: [
            {
              audio: {
                slot_id: "audio-pending-404a5ca0fb41382c",
              },
              cast_id: "narrator",
              id: "line-shot-8-2-2",
              line: {
                text: "Those slots can become graph nodes whose relations are updated by a latent GNN dynamics model.",
              },
            },
          ],
          duration: 11,
          elements: [],
          id: "shot-8-2",
          vo: {
            audio: {
              slot_id: "audio-pending-b90944412880b6a7",
            },
            cast_id: "narrator",
            line: {
              text: "Slot attention offers one route by assigning parts of an observation to a small set of latent slots.",
            },
          },
        },
        {
          duration: 6,
          elements: [],
          id: "shot-8-3",
          vo: {
            audio: {
              slot_id: "audio-pending-e6fe9fcdd847bea0",
            },
            cast_id: "narrator",
            line: {
              text: "The pipeline separates perception from simulation without requiring the final state to be a single monolithic vector.",
            },
          },
        },
        {
          duration: 6,
          elements: [],
          id: "shot-8-4",
          vo: {
            audio: {
              slot_id: "audio-pending-dcee0c28b5a0df6c",
            },
            cast_id: "narrator",
            line: {
              text: "Its promise is a world model that can discover entities from observations and then predict their interactions.",
            },
          },
        },
      ],
      summary: "Opener for Learning The Slots",
      title: "Learning The Slots",
    },
    {
      background: {
        kind: "gradient",
        stops: [
          {
            color: "#111827",
            offset: 0,
          },
          {
            color: "#db2777",
            offset: 1,
          },
        ],
      },
      eyebrow: "Objective Choice",
      id: "scene-what-to-train-for",
      shots: [
        {
          cues: [
            {
              at: 0,
              element_id: "narrator-opener.eyebrow",
              kind: "transform",
              layout: {
                opacity: 1,
              },
              transition: {
                duration_ms: 200,
                ease: "easeOut",
              },
            },
            {
              at: 0.15,
              element_id: "narrator-opener.title",
              kind: "transform",
              layout: {
                opacity: 1,
                position: [0.5, 0.5, 0],
              },
              transition: {
                duration_ms: 400,
                ease: "easeOut",
              },
            },
          ],
          duration: 4,
          elements: [
            {
              id: "narrator-opener.eyebrow",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.38, 0],
                z_order: 20,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#9ad1ff",
                font: "sans",
                size: "sm",
                weight: 700,
              },
              text: "Objective Choice",
            },
            {
              id: "narrator-opener.title",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.53, 0],
                z_order: 21,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#ffffff",
                font: "display",
                size: "4xl",
                weight: 800,
              },
              text: "What To Train For",
            },
          ],
          id: "shot-9-1",
          vo: {
            audio: {
              slot_id: "audio-pending-624e07e5de5ae99b",
            },
            cast_id: "narrator",
            line: {
              text: "A training objective decides what the latent graph is pressured to remember.",
            },
          },
        },
        {
          dialogue: [
            {
              audio: {
                slot_id: "audio-pending-3e43d435556ee587",
              },
              cast_id: "narrator",
              id: "line-shot-9-2-2",
              line: {
                text: "A contrastive objective can instead reward distinctions between plausible and implausible future states.",
              },
            },
          ],
          duration: 11,
          elements: [],
          id: "shot-9-2",
          vo: {
            audio: {
              slot_id: "audio-pending-05e18b8a9c57d3f1",
            },
            cast_id: "narrator",
            line: {
              text: "A reconstruction loss rewards states that can rebuild observations, including details that may not matter for control.",
            },
          },
        },
        {
          duration: 7,
          elements: [],
          id: "shot-9-3",
          vo: {
            audio: {
              slot_id: "audio-pending-9549bcec44cb97fc",
            },
            cast_id: "narrator",
            line: {
              text: "For graph world models, that difference shapes whether the representation preserves pixels, controllable factors, or relational structure.",
            },
          },
        },
        {
          duration: 6,
          elements: [],
          id: "shot-9-4",
          vo: {
            audio: {
              slot_id: "audio-pending-5f53d0816077ea4e",
            },
            cast_id: "narrator",
            line: {
              text: "The right objective depends on whether the learner needs faithful reconstruction, useful planning features, or robust generalization.",
            },
          },
        },
      ],
      summary: "Opener for What To Train For",
      title: "What To Train For",
    },
    {
      background: {
        kind: "gradient",
        stops: [
          {
            color: "#020617",
            offset: 0,
          },
          {
            color: "#4f46e5",
            offset: 1,
          },
        ],
      },
      eyebrow: "Planning Returns",
      id: "scene-search-in-the-graph",
      shots: [
        {
          cues: [
            {
              at: 0,
              element_id: "narrator-opener.eyebrow",
              kind: "transform",
              layout: {
                opacity: 1,
              },
              transition: {
                duration_ms: 200,
                ease: "easeOut",
              },
            },
            {
              at: 0.15,
              element_id: "narrator-opener.title",
              kind: "transform",
              layout: {
                opacity: 1,
                position: [0.5, 0.5, 0],
              },
              transition: {
                duration_ms: 400,
                ease: "easeOut",
              },
            },
          ],
          duration: 6,
          elements: [
            {
              id: "narrator-opener.eyebrow",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.38, 0],
                z_order: 20,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#9ad1ff",
                font: "sans",
                size: "sm",
                weight: 700,
              },
              text: "Planning Returns",
            },
            {
              id: "narrator-opener.title",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.53, 0],
                z_order: 21,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#ffffff",
                font: "display",
                size: "4xl",
                weight: 800,
              },
              text: "Search In The Graph",
            },
          ],
          id: "shot-10-1",
          vo: {
            audio: {
              slot_id: "audio-pending-78de42b71f2e4963",
            },
            cast_id: "narrator",
            line: {
              text: "Once a graph latent can predict future states, planning can search through possible actions inside that learned space.",
            },
          },
        },
        {
          dialogue: [
            {
              audio: {
                slot_id: "audio-pending-7f6b42c97af45f66",
              },
              cast_id: "narrator",
              id: "line-shot-10-2-2",
              line: {
                text: "Heuristic search adds guidance about which futures look promising before all branches are expanded.",
              },
            },
          ],
          duration: 12,
          elements: [],
          id: "shot-10-2",
          vo: {
            audio: {
              slot_id: "audio-pending-525ea2455dbe408f",
            },
            cast_id: "narrator",
            line: {
              text: "Model predictive control samples or optimizes short action sequences, scores their predicted futures, and executes the first action.",
            },
          },
        },
        {
          duration: 7,
          elements: [],
          id: "shot-10-3",
          vo: {
            audio: {
              slot_id: "audio-pending-ddea06de9985a1c1",
            },
            cast_id: "narrator",
            line: {
              text: "Monte Carlo tree search builds a tree of imagined graph states and uses repeated evaluations to choose the next move.",
            },
          },
        },
        {
          duration: 7,
          elements: [],
          id: "shot-10-4",
          vo: {
            audio: {
              slot_id: "audio-pending-3c9561be2638b27c",
            },
            cast_id: "narrator",
            line: {
              text: "All of these methods trade policy commitment for on-demand reasoning, while still paying the cost of model error and branching choices.",
            },
          },
        },
      ],
      summary: "Opener for Search In The Graph",
      title: "Search In The Graph",
    },
    {
      background: {
        kind: "gradient",
        stops: [
          {
            color: "#111827",
            offset: 0,
          },
          {
            color: "#0ea5e9",
            offset: 1,
          },
        ],
      },
      eyebrow: "Synthesis",
      id: "scene-connector-simulator-reasoner",
      shots: [
        {
          cues: [
            {
              at: 0,
              element_id: "narrator-opener.eyebrow",
              kind: "transform",
              layout: {
                opacity: 1,
              },
              transition: {
                duration_ms: 200,
                ease: "easeOut",
              },
            },
            {
              at: 0.15,
              element_id: "narrator-opener.title",
              kind: "transform",
              layout: {
                opacity: 1,
                position: [0.5, 0.5, 0],
              },
              transition: {
                duration_ms: 400,
                ease: "easeOut",
              },
            },
          ],
          duration: 5,
          elements: [
            {
              id: "narrator-opener.eyebrow",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.38, 0],
                z_order: 20,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#9ad1ff",
                font: "sans",
                size: "sm",
                weight: 700,
              },
              text: "Synthesis",
            },
            {
              id: "narrator-opener.title",
              initial_layout: {
                opacity: 0,
                position: [0.5, 0.53, 0],
                z_order: 21,
              },
              kind: "text-overlay",
              style: {
                align: "center",
                color: "#ffffff",
                font: "display",
                size: "4xl",
                weight: 800,
              },
              text: "Connector Simulator Reasoner",
            },
          ],
          id: "shot-11-1",
          vo: {
            audio: {
              slot_id: "audio-pending-85bb5871f0f2fee0",
            },
            cast_id: "narrator",
            line: {
              text: "By the end of the lesson, the graph has played three roles in the world model story.",
            },
          },
        },
        {
          dialogue: [
            {
              audio: {
                slot_id: "audio-pending-485116bfb39852fc",
              },
              cast_id: "narrator",
              id: "line-shot-11-2-2",
              line: {
                text: "As simulator, it uses message passing to update object states under actions.",
              },
            },
          ],
          duration: 10,
          elements: [],
          id: "shot-11-2",
          vo: {
            audio: {
              slot_id: "audio-pending-954c567039702046",
            },
            cast_id: "narrator",
            line: {
              text: "As connector, it names entities and relations so multi-object scenes can be represented compositionally.",
            },
          },
        },
        {
          duration: 5,
          elements: [],
          id: "shot-11-3",
          vo: {
            audio: {
              slot_id: "audio-pending-f9eea99e2d37a140",
            },
            cast_id: "narrator",
            line: {
              text: "As reasoner, it gives planners a structured space for comparing possible futures.",
            },
          },
        },
        {
          duration: 8,
          elements: [],
          id: "shot-11-4",
          vo: {
            audio: {
              slot_id: "audio-pending-12a833a7ac4f8388",
            },
            cast_id: "narrator",
            line: {
              text: "Each role introduces a tradeoff: stronger structure can improve generalization, but only when the learned entities, edges, and objectives match the task.",
            },
          },
        },
      ],
      summary: "Opener for Connector Simulator Reasoner",
      title: "Connector Simulator Reasoner",
    },
  ],
  summary: "Composer-generated production from ShotPlans.",
  tags: ["composer"],
  tier: "v0.1",
  title: "world-graph-models",
  transitions: [
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-model-before-policy",
        shot_id: "shot-1-1",
      },
      id: "transition.scene-model-before-policy.shot-1-1.to.scene-model-before-policy.shot-1-2",
      kind: "cut",
      to: {
        scene_id: "scene-model-before-policy",
        shot_id: "shot-1-2",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-model-before-policy",
        shot_id: "shot-1-2",
      },
      id: "transition.scene-model-before-policy.shot-1-2.to.scene-model-before-policy.shot-1-3",
      kind: "cut",
      to: {
        scene_id: "scene-model-before-policy",
        shot_id: "shot-1-3",
      },
    },
    {
      duration_ms: 600,
      "from": {
        scene_id: "scene-model-before-policy",
        shot_id: "shot-1-3",
      },
      id: "transition.scene-model-before-policy.shot-1-3.to.scene-dream-space.shot-2-1",
      kind: "cross-dissolve",
      to: {
        scene_id: "scene-dream-space",
        shot_id: "shot-2-1",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-dream-space",
        shot_id: "shot-2-1",
      },
      id: "transition.scene-dream-space.shot-2-1.to.scene-dream-space.shot-2-2",
      kind: "cut",
      to: {
        scene_id: "scene-dream-space",
        shot_id: "shot-2-2",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-dream-space",
        shot_id: "shot-2-2",
      },
      id: "transition.scene-dream-space.shot-2-2.to.scene-dream-space.shot-2-3",
      kind: "cut",
      to: {
        scene_id: "scene-dream-space",
        shot_id: "shot-2-3",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-dream-space",
        shot_id: "shot-2-3",
      },
      id: "transition.scene-dream-space.shot-2-3.to.scene-dream-space.shot-2-4",
      kind: "cut",
      to: {
        scene_id: "scene-dream-space",
        shot_id: "shot-2-4",
      },
    },
    {
      duration_ms: 600,
      "from": {
        scene_id: "scene-dream-space",
        shot_id: "shot-2-4",
      },
      id: "transition.scene-dream-space.shot-2-4.to.scene-error-horizon.shot-3-1",
      kind: "cross-dissolve",
      to: {
        scene_id: "scene-error-horizon",
        shot_id: "shot-3-1",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-error-horizon",
        shot_id: "shot-3-1",
      },
      id: "transition.scene-error-horizon.shot-3-1.to.scene-error-horizon.shot-3-2",
      kind: "cut",
      to: {
        scene_id: "scene-error-horizon",
        shot_id: "shot-3-2",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-error-horizon",
        shot_id: "shot-3-2",
      },
      id: "transition.scene-error-horizon.shot-3-2.to.scene-error-horizon.shot-3-3",
      kind: "cut",
      to: {
        scene_id: "scene-error-horizon",
        shot_id: "shot-3-3",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-error-horizon",
        shot_id: "shot-3-3",
      },
      id: "transition.scene-error-horizon.shot-3-3.to.scene-error-horizon.shot-3-4",
      kind: "cut",
      to: {
        scene_id: "scene-error-horizon",
        shot_id: "shot-3-4",
      },
    },
    {
      duration_ms: 600,
      "from": {
        scene_id: "scene-error-horizon",
        shot_id: "shot-3-4",
      },
      id: "transition.scene-error-horizon.shot-3-4.to.scene-combinatorial-wall.shot-4-1",
      kind: "cross-dissolve",
      to: {
        scene_id: "scene-combinatorial-wall",
        shot_id: "shot-4-1",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-combinatorial-wall",
        shot_id: "shot-4-1",
      },
      id: "transition.scene-combinatorial-wall.shot-4-1.to.scene-combinatorial-wall.shot-4-2",
      kind: "cut",
      to: {
        scene_id: "scene-combinatorial-wall",
        shot_id: "shot-4-2",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-combinatorial-wall",
        shot_id: "shot-4-2",
      },
      id: "transition.scene-combinatorial-wall.shot-4-2.to.scene-combinatorial-wall.shot-4-3",
      kind: "cut",
      to: {
        scene_id: "scene-combinatorial-wall",
        shot_id: "shot-4-3",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-combinatorial-wall",
        shot_id: "shot-4-3",
      },
      id: "transition.scene-combinatorial-wall.shot-4-3.to.scene-combinatorial-wall.shot-4-4",
      kind: "cut",
      to: {
        scene_id: "scene-combinatorial-wall",
        shot_id: "shot-4-4",
      },
    },
    {
      duration_ms: 600,
      "from": {
        scene_id: "scene-combinatorial-wall",
        shot_id: "shot-4-4",
      },
      id: "transition.scene-combinatorial-wall.shot-4-4.to.scene-relational-bias.shot-5-1",
      kind: "cross-dissolve",
      to: {
        scene_id: "scene-relational-bias",
        shot_id: "shot-5-1",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-relational-bias",
        shot_id: "shot-5-1",
      },
      id: "transition.scene-relational-bias.shot-5-1.to.scene-relational-bias.shot-5-2",
      kind: "cut",
      to: {
        scene_id: "scene-relational-bias",
        shot_id: "shot-5-2",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-relational-bias",
        shot_id: "shot-5-2",
      },
      id: "transition.scene-relational-bias.shot-5-2.to.scene-relational-bias.shot-5-3",
      kind: "cut",
      to: {
        scene_id: "scene-relational-bias",
        shot_id: "shot-5-3",
      },
    },
    {
      duration_ms: 600,
      "from": {
        scene_id: "scene-relational-bias",
        shot_id: "shot-5-3",
      },
      id: "transition.scene-relational-bias.shot-5-3.to.scene-message-passing-physics.shot-6-1",
      kind: "cross-dissolve",
      to: {
        scene_id: "scene-message-passing-physics",
        shot_id: "shot-6-1",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-message-passing-physics",
        shot_id: "shot-6-1",
      },
      id: "transition.scene-message-passing-physics.shot-6-1.to.scene-message-passing-physics.shot-6-2",
      kind: "cut",
      to: {
        scene_id: "scene-message-passing-physics",
        shot_id: "shot-6-2",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-message-passing-physics",
        shot_id: "shot-6-2",
      },
      id: "transition.scene-message-passing-physics.shot-6-2.to.scene-message-passing-physics.shot-6-3",
      kind: "cut",
      to: {
        scene_id: "scene-message-passing-physics",
        shot_id: "shot-6-3",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-message-passing-physics",
        shot_id: "shot-6-3",
      },
      id: "transition.scene-message-passing-physics.shot-6-3.to.scene-message-passing-physics.shot-6-4",
      kind: "cut",
      to: {
        scene_id: "scene-message-passing-physics",
        shot_id: "shot-6-4",
      },
    },
    {
      duration_ms: 600,
      "from": {
        scene_id: "scene-message-passing-physics",
        shot_id: "shot-6-4",
      },
      id: "transition.scene-message-passing-physics.shot-6-4.to.scene-order-does-not-matter.shot-7-1",
      kind: "cross-dissolve",
      to: {
        scene_id: "scene-order-does-not-matter",
        shot_id: "shot-7-1",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-order-does-not-matter",
        shot_id: "shot-7-1",
      },
      id: "transition.scene-order-does-not-matter.shot-7-1.to.scene-order-does-not-matter.shot-7-2",
      kind: "cut",
      to: {
        scene_id: "scene-order-does-not-matter",
        shot_id: "shot-7-2",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-order-does-not-matter",
        shot_id: "shot-7-2",
      },
      id: "transition.scene-order-does-not-matter.shot-7-2.to.scene-order-does-not-matter.shot-7-3",
      kind: "cut",
      to: {
        scene_id: "scene-order-does-not-matter",
        shot_id: "shot-7-3",
      },
    },
    {
      duration_ms: 600,
      "from": {
        scene_id: "scene-order-does-not-matter",
        shot_id: "shot-7-3",
      },
      id: "transition.scene-order-does-not-matter.shot-7-3.to.scene-learning-the-slots.shot-8-1",
      kind: "cross-dissolve",
      to: {
        scene_id: "scene-learning-the-slots",
        shot_id: "shot-8-1",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-learning-the-slots",
        shot_id: "shot-8-1",
      },
      id: "transition.scene-learning-the-slots.shot-8-1.to.scene-learning-the-slots.shot-8-2",
      kind: "cut",
      to: {
        scene_id: "scene-learning-the-slots",
        shot_id: "shot-8-2",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-learning-the-slots",
        shot_id: "shot-8-2",
      },
      id: "transition.scene-learning-the-slots.shot-8-2.to.scene-learning-the-slots.shot-8-3",
      kind: "cut",
      to: {
        scene_id: "scene-learning-the-slots",
        shot_id: "shot-8-3",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-learning-the-slots",
        shot_id: "shot-8-3",
      },
      id: "transition.scene-learning-the-slots.shot-8-3.to.scene-learning-the-slots.shot-8-4",
      kind: "cut",
      to: {
        scene_id: "scene-learning-the-slots",
        shot_id: "shot-8-4",
      },
    },
    {
      duration_ms: 600,
      "from": {
        scene_id: "scene-learning-the-slots",
        shot_id: "shot-8-4",
      },
      id: "transition.scene-learning-the-slots.shot-8-4.to.scene-what-to-train-for.shot-9-1",
      kind: "cross-dissolve",
      to: {
        scene_id: "scene-what-to-train-for",
        shot_id: "shot-9-1",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-what-to-train-for",
        shot_id: "shot-9-1",
      },
      id: "transition.scene-what-to-train-for.shot-9-1.to.scene-what-to-train-for.shot-9-2",
      kind: "cut",
      to: {
        scene_id: "scene-what-to-train-for",
        shot_id: "shot-9-2",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-what-to-train-for",
        shot_id: "shot-9-2",
      },
      id: "transition.scene-what-to-train-for.shot-9-2.to.scene-what-to-train-for.shot-9-3",
      kind: "cut",
      to: {
        scene_id: "scene-what-to-train-for",
        shot_id: "shot-9-3",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-what-to-train-for",
        shot_id: "shot-9-3",
      },
      id: "transition.scene-what-to-train-for.shot-9-3.to.scene-what-to-train-for.shot-9-4",
      kind: "cut",
      to: {
        scene_id: "scene-what-to-train-for",
        shot_id: "shot-9-4",
      },
    },
    {
      duration_ms: 600,
      "from": {
        scene_id: "scene-what-to-train-for",
        shot_id: "shot-9-4",
      },
      id: "transition.scene-what-to-train-for.shot-9-4.to.scene-search-in-the-graph.shot-10-1",
      kind: "cross-dissolve",
      to: {
        scene_id: "scene-search-in-the-graph",
        shot_id: "shot-10-1",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-search-in-the-graph",
        shot_id: "shot-10-1",
      },
      id: "transition.scene-search-in-the-graph.shot-10-1.to.scene-search-in-the-graph.shot-10-2",
      kind: "cut",
      to: {
        scene_id: "scene-search-in-the-graph",
        shot_id: "shot-10-2",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-search-in-the-graph",
        shot_id: "shot-10-2",
      },
      id: "transition.scene-search-in-the-graph.shot-10-2.to.scene-search-in-the-graph.shot-10-3",
      kind: "cut",
      to: {
        scene_id: "scene-search-in-the-graph",
        shot_id: "shot-10-3",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-search-in-the-graph",
        shot_id: "shot-10-3",
      },
      id: "transition.scene-search-in-the-graph.shot-10-3.to.scene-search-in-the-graph.shot-10-4",
      kind: "cut",
      to: {
        scene_id: "scene-search-in-the-graph",
        shot_id: "shot-10-4",
      },
    },
    {
      duration_ms: 600,
      "from": {
        scene_id: "scene-search-in-the-graph",
        shot_id: "shot-10-4",
      },
      id: "transition.scene-search-in-the-graph.shot-10-4.to.scene-connector-simulator-reasoner.shot-11-1",
      kind: "cross-dissolve",
      to: {
        scene_id: "scene-connector-simulator-reasoner",
        shot_id: "shot-11-1",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-connector-simulator-reasoner",
        shot_id: "shot-11-1",
      },
      id: "transition.scene-connector-simulator-reasoner.shot-11-1.to.scene-connector-simulator-reasoner.shot-11-2",
      kind: "cut",
      to: {
        scene_id: "scene-connector-simulator-reasoner",
        shot_id: "shot-11-2",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-connector-simulator-reasoner",
        shot_id: "shot-11-2",
      },
      id: "transition.scene-connector-simulator-reasoner.shot-11-2.to.scene-connector-simulator-reasoner.shot-11-3",
      kind: "cut",
      to: {
        scene_id: "scene-connector-simulator-reasoner",
        shot_id: "shot-11-3",
      },
    },
    {
      duration_ms: 0,
      "from": {
        scene_id: "scene-connector-simulator-reasoner",
        shot_id: "shot-11-3",
      },
      id: "transition.scene-connector-simulator-reasoner.shot-11-3.to.scene-connector-simulator-reasoner.shot-11-4",
      kind: "cut",
      to: {
        scene_id: "scene-connector-simulator-reasoner",
        shot_id: "shot-11-4",
      },
    },
  ],
};

export const MANIFEST: AssetManifest = {
  ledger: [],
  production_id: "world-graph-models",
  slots: {
    "audio-pending-028aff37b8904164": {
      description: "Voiceover for narrator: Object slots and graph nodes often arrive in an arbitrary order.",
      id: "audio-pending-028aff37b8904164",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-05e18b8a9c57d3f1": {
      description: "Voiceover for narrator: A reconstruction loss rewards states that can rebuild observations, including...",
      id: "audio-pending-05e18b8a9c57d3f1",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-12a833a7ac4f8388": {
      description: "Voiceover for narrator: Each role introduces a tradeoff: stronger structure can improve generalizatio...",
      id: "audio-pending-12a833a7ac4f8388",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-1b28307ebed8d60f": {
      description: "Voiceover for narrator: It should not predict a different collision merely because object three was r...",
      id: "audio-pending-1b28307ebed8d60f",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-1fcfa4ce83be9fd9": {
      description: "Voiceover for narrator: A graph builds an assumption into the model: entities are nodes, and possible...",
      id: "audio-pending-1fcfa4ce83be9fd9",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-234b1b4219a0d0f0": {
      description: "Voiceover for narrator: A one-step prediction can look accurate while still carrying a small error in...",
      id: "audio-pending-234b1b4219a0d0f0",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-2b568ae74c33ebaf": {
      description: "Voiceover for narrator: This is the combinatorial wall that pushes world models toward objects and re...",
      id: "audio-pending-2b568ae74c33ebaf",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-3339b73b08d12087": {
      description: "Voiceover for narrator: A permutation-equivariant graph model respects that fact by moving prediction...",
      id: "audio-pending-3339b73b08d12087",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-34422d701b866cd0": {
      description: "Voiceover for narrator: Latent imagination is useful because it makes planning and policy learning fa...",
      id: "audio-pending-34422d701b866cd0",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-35f100d4f1512217": {
      description: "Voiceover for narrator: Generalization comes from treating relations as repeatable structure, not as ...",
      id: "audio-pending-35f100d4f1512217",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-39d5f0693bab3457": {
      description: "Voiceover for narrator: A learned world model changes that bargain by turning past experience into a ...",
      id: "audio-pending-39d5f0693bab3457",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-3b5d89feda8f41a6": {
      description: "Voiceover for narrator: If two identical descriptions are listed in a different order, the world has ...",
      id: "audio-pending-3b5d89feda8f41a6",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-3c9561be2638b27c": {
      description: "Voiceover for narrator: All of these methods trade policy commitment for on-demand reasoning, while s...",
      id: "audio-pending-3c9561be2638b27c",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-3e43d435556ee587": {
      description: "Voiceover for narrator: A contrastive objective can instead reward distinctions between plausible and...",
      id: "audio-pending-3e43d435556ee587",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-3f056baf1756b3df": {
      description: "Voiceover for narrator: Inside that compressed space, rollout steps are cheaper than replaying the fu...",
      id: "audio-pending-3f056baf1756b3df",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-404a5ca0fb41382c": {
      description: "Voiceover for narrator: Those slots can become graph nodes whose relations are updated by a latent GN...",
      id: "audio-pending-404a5ca0fb41382c",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-485116bfb39852fc": {
      description: "Voiceover for narrator: As simulator, it uses message passing to update object states under actions.",
      id: "audio-pending-485116bfb39852fc",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-4f037fc5db31a287": {
      description: "Voiceover for narrator: Sample efficiency improves when useful policy updates come from both real int...",
      id: "audio-pending-4f037fc5db31a287",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-525ea2455dbe408f": {
      description: "Voiceover for narrator: Model predictive control samples or optimizes short action sequences, scores ...",
      id: "audio-pending-525ea2455dbe408f",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-5f53d0816077ea4e": {
      description: "Voiceover for narrator: The right objective depends on whether the learner needs faithful reconstruct...",
      id: "audio-pending-5f53d0816077ea4e",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-624e07e5de5ae99b": {
      description: "Voiceover for narrator: A training objective decides what the latent graph is pressured to remember.",
      id: "audio-pending-624e07e5de5ae99b",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-78de42b71f2e4963": {
      description: "Voiceover for narrator: Once a graph latent can predict future states, planning can search through po...",
      id: "audio-pending-78de42b71f2e4963",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-7f6b42c97af45f66": {
      description: "Voiceover for narrator: Heuristic search adds guidance about which futures look promising before all ...",
      id: "audio-pending-7f6b42c97af45f66",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-817c59e419365f29": {
      description: "Voiceover for narrator: Message passing acts like learned local physics because future motion emerges...",
      id: "audio-pending-817c59e419365f29",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-85bb5871f0f2fee0": {
      description: "Voiceover for narrator: By the end of the lesson, the graph has played three roles in the world model...",
      id: "audio-pending-85bb5871f0f2fee0",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-893fafccd1167f10": {
      description: "Voiceover for narrator: In a graph dynamics model, prediction begins with object states and an action...",
      id: "audio-pending-893fafccd1167f10",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-8a7e1525f87236ec": {
      description: "Voiceover for narrator: The same imagination that saves samples also creates a new failure mode.",
      id: "audio-pending-8a7e1525f87236ec",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-8ba2cecf87512e78": {
      description: "Voiceover for narrator: The model can then ask how these entities relate instead of relearning every ...",
      id: "audio-pending-8ba2cecf87512e78",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-8f56dcd274cad430": {
      description: "Voiceover for narrator: As the number of objects grows, the possible arrangements and interactions gr...",
      id: "audio-pending-8f56dcd274cad430",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-9298caa4b524616e": {
      description: "Voiceover for narrator: The shared dynamics rule updates every object into a predicted next state.",
      id: "audio-pending-9298caa4b524616e",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-945a45d42f124856": {
      description: "Voiceover for narrator: Long imagined rollouts therefore have an error horizon where useful forecasts...",
      id: "audio-pending-945a45d42f124856",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-9549bcec44cb97fc": {
      description: "Voiceover for narrator: For graph world models, that difference shapes whether the representation pre...",
      id: "audio-pending-9549bcec44cb97fc",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-954c567039702046": {
      description: "Voiceover for narrator: As connector, it names entities and relations so multi-object scenes can be r...",
      id: "audio-pending-954c567039702046",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-9a89ba2c429c44db": {
      description: "Voiceover for narrator: The same update rule can be shared across many pairs of objects instead of be...",
      id: "audio-pending-9a89ba2c429c44db",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-9e981a90f496937d": {
      description: "Voiceover for narrator: An object-centric world model first has to find the objects before it can rea...",
      id: "audio-pending-9e981a90f496937d",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-a81ca8e619ba66e8": {
      description: "Voiceover for narrator: The agent can ask the model for imagined transitions before it commits to ano...",
      id: "audio-pending-a81ca8e619ba66e8",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-ac090a786eb2c74d": {
      description: "Voiceover for narrator: A latent world model does not need to store every pixel as the agent sees it.",
      id: "audio-pending-ac090a786eb2c74d",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-ac1c6acc2e3b2775": {
      description: "Voiceover for narrator: The price is that the model must choose which entities and edges deserve atte...",
      id: "audio-pending-ac1c6acc2e3b2775",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-aee1c79da73eb49b": {
      description: "Voiceover for narrator: A single-vector latent state can summarize a scene, but it does not naturally...",
      id: "audio-pending-aee1c79da73eb49b",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-b290d66327718ef9": {
      description: "Voiceover for narrator: An object-centric representation breaks the scene into reusable entities with...",
      id: "audio-pending-b290d66327718ef9",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-b48739eead614cf7": {
      description: "Voiceover for narrator: When the model feeds its own prediction into the next prediction, that small ...",
      id: "audio-pending-b48739eead614cf7",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-b6b08b2e87f04a9e": {
      description: "Voiceover for narrator: Order does not matter, but consistent correspondence does.",
      id: "audio-pending-b6b08b2e87f04a9e",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-b90944412880b6a7": {
      description: "Voiceover for narrator: Slot attention offers one route by assigning parts of an observation to a sma...",
      id: "audio-pending-b90944412880b6a7",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-b9880e9b08f54375": {
      description: "Voiceover for narrator: A reinforcement learning agent normally pays for knowledge with real trials, ...",
      id: "audio-pending-b9880e9b08f54375",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-d64319b617f9ede3": {
      description: "Voiceover for narrator: A receiving node aggregates those messages with its own state and the action ...",
      id: "audio-pending-d64319b617f9ede3",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-daf01f6c4d2192ce": {
      description: "Voiceover for narrator: The opening question is not whether the model is perfect, but whether it is g...",
      id: "audio-pending-daf01f6c4d2192ce",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-dcee0c28b5a0df6c": {
      description: "Voiceover for narrator: Its promise is a world model that can discover entities from observations and...",
      id: "audio-pending-dcee0c28b5a0df6c",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-ddea06de9985a1c1": {
      description: "Voiceover for narrator: Monte Carlo tree search builds a tree of imagined graph states and uses repea...",
      id: "audio-pending-ddea06de9985a1c1",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-de8b6f0a6c5a5ee6": {
      description: "Voiceover for narrator: It learns a compact state that keeps the information needed to predict reward...",
      id: "audio-pending-de8b6f0a6c5a5ee6",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-e6fe9fcdd847bea0": {
      description: "Voiceover for narrator: The pipeline separates perception from simulation without requiring the final...",
      id: "audio-pending-e6fe9fcdd847bea0",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-e8754f50ce774194": {
      description: "Voiceover for narrator: A policy can train inside those predicted futures and test many action sequen...",
      id: "audio-pending-e8754f50ce774194",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-f174f2ecc4d9cd87": {
      description: "Voiceover for narrator: That relational inductive bias helps the model reuse a learned interaction wh...",
      id: "audio-pending-f174f2ecc4d9cd87",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-f9eea99e2d37a140": {
      description: "Voiceover for narrator: As reasoner, it gives planners a structured space for comparing possible futu...",
      id: "audio-pending-f9eea99e2d37a140",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-fb76c8d8fa66e005": {
      description: "Voiceover for narrator: Each node sends messages along its edges that describe how it may influence i...",
      id: "audio-pending-fb76c8d8fa66e005",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
    "audio-pending-fd2eb5862ba7790e": {
      description: "Voiceover for narrator: Good model-based control must balance the value of looking ahead against the ...",
      id: "audio-pending-fd2eb5862ba7790e",
      kind: "audio-vo",
      selection: "best-available",
      takes: [],
    },
  },
};
