import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
export function StepThrough({ steps }) {
    const [i, setI] = useState(0);
    const atStart = i === 0;
    const atEnd = i === steps.length - 1;
    return (_jsxs("div", { className: "my-8 rounded-2xl border border-ink-subtle/15 bg-paper-card overflow-hidden shadow-card", children: [_jsxs("div", { className: "px-5 py-3 border-b border-ink-subtle/10 bg-paper-tint flex items-center justify-between", children: [_jsxs("p", { className: "font-mono text-xs uppercase tracking-[0.12em] text-ink-muted", children: ["Step ", i + 1, " of ", steps.length] }), _jsx("div", { className: "flex gap-1", children: steps.map((_, n) => (_jsx("span", { className: `h-1.5 w-6 rounded-full transition ${n === i ? 'bg-accent' : n < i ? 'bg-accent/40' : 'bg-ink-subtle/20'}` }, n))) })] }), _jsx("div", { className: "p-6 min-h-[160px]", children: _jsx(AnimatePresence, { mode: "wait", children: _jsxs(motion.div, { initial: { opacity: 0, x: 12 }, animate: { opacity: 1, x: 0 }, exit: { opacity: 0, x: -12 }, transition: { duration: 0.25 }, children: [steps[i].title && (_jsx("h3", { className: "font-display text-lg font-semibold mb-3", children: steps[i].title })), _jsx("div", { className: "text-ink/90", children: steps[i].content })] }, i) }) }), _jsxs("div", { className: "px-5 py-3 border-t border-ink-subtle/10 flex justify-between bg-paper-tint/40", children: [_jsx("button", { onClick: () => setI((n) => Math.max(0, n - 1)), disabled: atStart, className: "font-mono text-xs uppercase tracking-[0.12em] text-ink-muted disabled:opacity-30 disabled:cursor-not-allowed hover:text-ink", children: "\u2190 Back" }), _jsx("button", { onClick: () => setI((n) => Math.min(steps.length - 1, n + 1)), disabled: atEnd, className: "font-mono text-xs uppercase tracking-[0.12em] text-accent disabled:opacity-30 disabled:cursor-not-allowed hover:text-accent-hover", children: atEnd ? 'End' : 'Next →' })] })] }));
}
