import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { LessonShell, Section, Callout, Quiz, Diagram, Math, Plot, Slider, Sandbox, StepThrough, MatchPairs, Reveal, KeyTerm, FreeResponse, AIVideo, } from '@/components';
function OhmsLawSandbox() {
    const [voltage, setVoltage] = useState(12);
    const [resistance, setResistance] = useState(100);
    const current = voltage / resistance;
    return (_jsx(Sandbox, { title: "Ohm's law sandbox", controls: _jsxs("div", { className: "grid grid-cols-2 gap-6", children: [_jsx(Slider, { label: "Voltage", min: 0, max: 24, step: 0.5, value: voltage, onChange: setVoltage, unit: "V" }), _jsx(Slider, { label: "Resistance", min: 10, max: 1000, step: 10, value: resistance, onChange: setResistance, unit: "\u03A9" })] }), children: _jsxs("div", { className: "text-center py-6", children: [_jsx("p", { className: "font-mono text-xs uppercase tracking-[0.18em] text-ink-muted mb-2", children: "Current" }), _jsxs("p", { className: "font-display text-5xl font-semibold text-accent tabular-nums", children: [(current * 1000).toFixed(1), _jsx("span", { className: "text-2xl text-ink-muted ml-1", children: "mA" })] }), _jsx("div", { className: "mt-4 text-ink-muted", children: _jsx(Math, { expr: `I = \\frac{V}{R} = \\frac{${voltage}}{${resistance}}` }) })] }) }));
}
export default function Welcome() {
    return (_jsxs(LessonShell, { title: "Welcome to the Learning Tool", subtitle: "A quick tour of every component, using one running example: electricity.", kicker: "GETTING STARTED", estimatedMinutes: 6, children: [_jsxs(Section, { eyebrow: "Part 1", title: "The hook", children: [_jsx("p", { children: "When you flip a light switch, something invisible races down a wire at nearly the speed of light, hits a bulb, and turns into a photon you can see. That whole journey is governed by just three quantities \u2014 and the relationship between them is so simple you can fit it on a postage stamp." }), _jsxs("p", { children: ["By the end of this 6-minute tour you'll understand ", _jsx(KeyTerm, { term: "Ohm's law", definition: "V = IR \u2014 voltage equals current times resistance. The single most-used equation in electronics." }), ", and you'll have seen every component this tool gives an AI to build lessons."] }), _jsx(Callout, { kind: "insight", title: "What you're looking at", children: _jsxs("p", { children: ["This page is a single ", _jsx("code", { children: ".tsx" }), " file. An AI wrote it by calling a small set of tools. Everything you see \u2014 the math, the chart, the interactive sandbox \u2014 is composed from a curated library so lessons stay consistent."] }) })] }), _jsxs(Section, { eyebrow: "Part 2", title: "The three quantities", children: [_jsx("p", { children: "Three things tell the whole story:" }), _jsx(Diagram, { chart: `flowchart LR
  V[Voltage<br/>'pressure'] --> R[Resistance<br/>'narrow pipe']
  R --> I[Current<br/>'flow']
  style V fill:#ede9fe,stroke:#5b21b6
  style R fill:#fef3c7,stroke:#f59e0b
  style I fill:#dcfce7,stroke:#10b981`, caption: "A useful (if imperfect) analogy: voltage pushes, resistance squeezes, current flows." }), _jsx(MatchPairs, { pairs: [
                            { left: 'Voltage (V)', right: 'Electrical pressure — what pushes charge' },
                            { left: 'Current (I)', right: 'Rate of charge flow, measured in amps' },
                            { left: 'Resistance (R)', right: 'How much the wire resists the flow' },
                        ] })] }), _jsxs(Section, { eyebrow: "Part 3", title: "One equation to rule them all", children: [_jsx("p", { children: "The relationship between the three is shockingly simple:" }), _jsx(Math, { display: true, expr: "V = I \\cdot R" }), _jsxs("p", { children: ["Read it like a sentence: ", _jsx("em", { children: "voltage equals current times resistance" }), ". Which means if you know any two, you can solve for the third."] }), _jsx(StepThrough, { steps: [
                            {
                                title: '1. You have a 9 V battery and a 470 Ω resistor.',
                                content: (_jsxs("p", { children: ["You want to know how much current will flow. You have V and R, you need I. Rearrange:", ' ', _jsx(Math, { expr: "I = V / R" }), "."] })),
                            },
                            {
                                title: '2. Plug in.',
                                content: (_jsxs("p", { children: [_jsx(Math, { expr: "I = 9 / 470 \\approx 0.019\\,\\text{A} = 19\\,\\text{mA}" }), ". That's a comfortable current for a typical LED."] })),
                            },
                            {
                                title: '3. Sanity check.',
                                content: (_jsx("p", { children: "Doubling the voltage to 18 V would double the current to ~38 mA. Halving the resistance would also double it. Linear in both. That's the entire law." })),
                            },
                        ] })] }), _jsxs(Section, { eyebrow: "Part 4", title: "Play with it", children: [_jsx("p", { children: "Reading about a linear relationship is one thing. Feeling it is another. Drag the sliders. Notice how doubling voltage doubles current \u2014 and how a small change in resistance moves current a lot." }), _jsx(OhmsLawSandbox, {}), _jsx(FreeResponse, { prompt: "If you keep the voltage constant at 12 V and you want to halve the current, what do you do to the resistance?", sampleAnswer: "Double it. Since I = V/R and V is fixed, current is inversely proportional to resistance. Doubling R halves I." })] }), _jsxs(Section, { eyebrow: "Part 5", title: "A picture of the law", children: [_jsxs("p", { children: ["When you hold resistance fixed and sweep voltage, you get a straight line through the origin. The slope is ", _jsx(Math, { expr: "1/R" }), ". Steeper line = less resistance."] }), _jsx(Plot, { data: [
                            { v: 0, '100Ω': 0, '500Ω': 0 },
                            { v: 2, '100Ω': 0.02, '500Ω': 0.004 },
                            { v: 4, '100Ω': 0.04, '500Ω': 0.008 },
                            { v: 6, '100Ω': 0.06, '500Ω': 0.012 },
                            { v: 8, '100Ω': 0.08, '500Ω': 0.016 },
                            { v: 10, '100Ω': 0.1, '500Ω': 0.02 },
                            { v: 12, '100Ω': 0.12, '500Ω': 0.024 },
                        ], x: "v", y: ['100Ω', '500Ω'], legend: true, caption: "Two resistors, same law. The 100 \u03A9 resistor passes 5\u00D7 as much current at any given voltage." })] }), _jsxs(Section, { eyebrow: "Part 6", title: "Check yourself", children: [_jsx(Quiz, { question: "A circuit has a 5 V source and a 1 k\u03A9 resistor. What is the current?", options: ['5 A', '5 mA', '0.5 A', '5 µA'], correct: 1, explanation: "I = V/R = 5 V / 1000 \u03A9 = 0.005 A = 5 mA. The trick is unit-tracking \u2014 voltage in volts, resistance in ohms, current comes out in amps. 5 mA is small but very normal for hobby electronics." }), _jsx("p", { children: "Here's a question that needs a moment of thought:" }), _jsx("p", { className: "my-3", children: "You connect a wire directly across a battery (no resistor \u2014 just a wire). What does Ohm's law predict?" }), _jsx(Reveal, { label: "Show the answer", children: _jsxs("p", { children: ["With R near zero, the predicted current goes to infinity. In reality the wire heats up, its resistance climbs, and either the battery dies very fast or something melts. That's what a ", _jsx("strong", { children: "short circuit" }), " is \u2014 a stark reminder that the law assumes a non-zero resistance."] }) })] }), _jsxs(Section, { eyebrow: "Coming soon", title: "Video, when we get there", children: [_jsx("p", { children: "Eventually, lessons will be able to drop in short generated clips wherever a video would help the explanation. For now, the placeholder marks the spot:" }), _jsx(AIVideo, { prompt: "A slow-motion close-up of electrons drifting through a copper wire, isometric view, soft purple lighting", duration: 5, caption: "An animated electron drift \u2014 useful where prose alone doesn't move." })] }), _jsxs(Section, { eyebrow: "Wrap", title: "That's the tour", children: [_jsxs("p", { children: ["You just experienced every component this tool exposes: ", _jsx("code", { children: "LessonShell" }), ",", ' ', _jsx("code", { children: "Section" }), ", ", _jsx("code", { children: "Callout" }), ", ", _jsx("code", { children: "Math" }), ", ", _jsx("code", { children: "Diagram" }), ",", ' ', _jsx("code", { children: "MatchPairs" }), ", ", _jsx("code", { children: "StepThrough" }), ", ", _jsx("code", { children: "Sandbox" }), " +", ' ', _jsx("code", { children: "Slider" }), ", ", _jsx("code", { children: "FreeResponse" }), ", ", _jsx("code", { children: "Plot" }), ", ", _jsx("code", { children: "Quiz" }), ",", ' ', _jsx("code", { children: "Reveal" }), ", ", _jsx("code", { children: "KeyTerm" }), ", and ", _jsx("code", { children: "AIVideo" }), "."] }), _jsxs("p", { children: ["Now ask an AI to make you a lesson on something you actually want to learn. The AI will read the catalog, follow the same conventions, and write its own ", _jsx("code", { children: ".tsx" }), " file \u2014 and a few seconds later you'll have a new entry on the index page."] })] })] }));
}
