import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { listLessonsWithMeta } from './lessons-glob';
export default function LessonIndex() {
    const [lessons, setLessons] = useState([]);
    useEffect(() => {
        listLessonsWithMeta().then(setLessons);
    }, []);
    return (_jsx("main", { className: "min-h-screen px-6 py-16", children: _jsxs("div", { className: "mx-auto max-w-3xl", children: [_jsxs("header", { className: "mb-12", children: [_jsx("p", { className: "font-mono text-xs uppercase tracking-[0.18em] text-accent mb-3", children: "Learning Tool" }), _jsx("h1", { className: "font-display text-5xl font-semibold tracking-tight", children: "Your lessons" }), _jsx("p", { className: "mt-4 text-ink-muted text-lg", children: "Interactive learning artifacts generated by AI." })] }), lessons.length === 0 ? (_jsxs("div", { className: "rounded-2xl border border-dashed border-ink-subtle/40 bg-paper-card p-10 text-center", children: [_jsx("p", { className: "text-ink-muted", children: "No lessons yet. Ask an AI to make one." }), _jsx("p", { className: "mt-2 font-mono text-xs text-ink-subtle", children: "Try: \"make me a lesson about how a transistor works\"" })] })) : (_jsx("ul", { className: "grid gap-3", children: lessons.map((l) => (_jsx("li", { children: _jsxs(Link, { to: `/lesson/${l.slug}`, className: "block rounded-2xl border border-ink-subtle/20 bg-paper-card p-5 shadow-card transition hover:border-accent/40 hover:shadow-md", children: [_jsxs("div", { className: "flex items-baseline justify-between gap-4", children: [_jsx("h2", { className: "font-display text-xl font-semibold", children: l.title }), l.createdAt && (_jsx("time", { className: "font-mono text-xs text-ink-subtle whitespace-nowrap", children: new Date(l.createdAt).toLocaleDateString() }))] }), l.summary && _jsx("p", { className: "mt-1 text-ink-muted", children: l.summary })] }) }, l.slug))) }))] }) }));
}
