import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { listLessonsWithMeta, type LessonMeta } from './lessons-glob';

type Entry = LessonMeta & { slug: string };

export default function LessonIndex() {
  const [lessons, setLessons] = useState<Entry[]>([]);

  useEffect(() => {
    listLessonsWithMeta().then(setLessons);
  }, []);

  return (
    <main className="h-[100svh] max-h-[100svh] flex flex-col overflow-hidden">
      <div className="flex-1 min-h-0 overflow-y-auto overscroll-contain px-6 py-16 mx-auto w-full max-w-3xl">
        <header className="mb-12">
          <p className="font-mono text-xs uppercase tracking-[0.18em] text-accent mb-3">
            Learning Tool
          </p>
          <h1 className="font-display text-5xl font-semibold tracking-tight">Your lessons</h1>
          <p className="mt-4 text-ink-muted text-lg">
            Interactive learning artifacts generated by AI.
          </p>
        </header>

        {lessons.length === 0 ? (
          <div className="rounded-2xl border border-dashed border-ink-subtle/40 bg-paper-card p-10 text-center">
            <p className="text-ink-muted">No lessons yet. Ask an AI to make one.</p>
            <p className="mt-2 font-mono text-xs text-ink-subtle">
              Try: "make me a lesson about how a transistor works"
            </p>
          </div>
        ) : (
          <ul className="grid gap-3">
            {lessons.map((l) => (
              <li key={l.slug}>
                <Link
                  to={`/lesson/${l.slug}`}
                  className="block rounded-2xl border border-ink-subtle/20 bg-paper-card p-5 shadow-card transition hover:border-accent/40 hover:shadow-md"
                >
                  <div className="flex items-baseline justify-between gap-4">
                    <h2 className="font-display text-xl font-semibold">{l.title}</h2>
                    {l.createdAt && (
                      <time className="font-mono text-xs text-ink-subtle whitespace-nowrap">
                        {new Date(l.createdAt).toLocaleDateString()}
                      </time>
                    )}
                  </div>
                  {l.summary && <p className="mt-1 text-ink-muted">{l.summary}</p>}
                </Link>
              </li>
            ))}
          </ul>
        )}
      </div>
    </main>
  );
}
